### ISSUE TITLE
Install directories messed up

### ISSUE THREAD

**Issue by nylocx** [Aseman-Land/libqtelegram-aseman-edition#16]
Hi, I co-Maintain the libqtelegram-ae packages on the Arch User Repository and I noticed that the packages are currently broken due to a bug in the header install routine.

With commit 31bb7bcdfd757904b0cfc129458e23920bbca8d9 the PREFIX variable got removed so I no longer see a way to customize the INSTALL_PREFIX variable (Yes I know I could use sed in my build script, but I'm talking about official solutions here) which will make the packages non compliant with the Arch packaging standard as it is not good practice to install into the qt directory on the target system. 
The second change that messed it up even more for me is: a40c2b755ed0dd99b618255d48373f2ecc3ea334

By replacing the directory references with $$PWD the paths now extend to my build jail path which would be ok if not they where used by the install routine to install header files in [qmake/headerinstall.pri](../blob/master/qmake/headerinstall.pri).
This leads to install paths like "/usr/include/qt/libqtelegram-ae/tmp/makepkg/libqtelegram-ae-git/src/libqtelegram-ae-git/telegram/types/types.h" for my system.

I hope the problem got clear if you have any more questions pleas feel free to ask.

**Comment by realbardia** [comment]
Hi
Sorry for the problem. The problem is fixed now. You can use PREFIX again. It will install headers in the PREFIX/include and lib in the PREFIX/lib/(architecture)-linux-gnu
Did it fix the problem?

**Comment by nylocx** [comment]
First of all thanks for the quick response.

> Did it fix the problem?

Almost ;)
IMHO using a architecture specific directory for the libraries is debian or even ubuntu specific
1c4e0d7005809a541000d4244238f5c57ff2f175#diff-99345e3cc43efe6e02a4db58c9e84b5dL18

Arch Linux follows the Filesystem Hierarchy Standard (FHS) more closely and uses /usr/lib for the libraries. Put that is something I can handle by patching the pro file via sed if it is out of scope for you.

**Comment by realbardia** [comment]
I add two new variables in the pro file to set libs and header prefix path manualy:

```
INSTALL_LIBS_PREFIX
INSTALL_HEADERS_PREFIX
```

Does these variables resolve the issue?

**Comment by nylocx** [comment]
Hi,

> Does these variables resolve the issue?

Yes it would ;) but there are some typos. Sorry
[Line 27](https://github.com/Aseman-Land/libqtelegram-aseman-edition/blob/70ef02a0b1aea90ae8177442a30d797040da4a8c/libqtelegram-ae.pro#L27)
the second INSTALL_HEADERS_PREFIX is actually INSTALL_HEADE_PREFIXR.

And [Line 30](https://github.com/Aseman-Land/libqtelegram-aseman-edition/blob/70ef02a0b1aea90ae8177442a30d797040da4a8c/libqtelegram-ae.pro#L30) is missing an S in
INSTALL_HEADER_PREFIX

**Comment by realbardia** [comment]
All fixed :)

**Comment by nylocx** [comment]
Thanks, for the quick fix and have a nice day. I go ahead and close that one and go to check the telegramqml build.

**Comment by Techwolf** [comment]
Please release these soon in a tag. I'me currently using a workaround of eqmake5 PREFIX="${EPREFIX}/usr" INSTALL_HEADERS_PREFIX="${EPREFIX}/usr/include"

I'me sure other packagers that are using the download zip/tarball feature here are going to get bit with this bug.

**Comment by realbardia** [comment]
All tags updated to the last commits. you can using them.
Thank you for reporting :)
