### ISSUE TITLE
Request stable tag due new 2.7.0 cutegram release and 0.6.0 TelegramQML

### ISSUE THREAD

**Issue by heliocastro** [Aseman-Land/libqtelegram-aseman-edition#17]
Hi

Some headers presented only on head are required to new releases, so maybe is a good idea tag the code > 0.5.0 now, to make easier create the packages.
For now in fedora i'm packing maste with fake 0.5.1 version until we have proper one.

**Comment by realbardia** [comment]
Hi...
All tags updated to the last commits.

```
libqtelegram-ae: v6.0-stable
telegramqml: v0.9.1-stable
cutegram: v2.7.0-stable
```

**Comment by heliocastro** [comment]
Many thanks

**Comment by realbardia** [comment]
Thank you too for creating the packages...
