### ISSUE TITLE
2 Factor Authentication does not work

### ISSUE THREAD

**Issue by no-identd** [Aseman-Land/libqtelegram-aseman-edition#53]
Since this is actually alibqtelegram-aseman-edition issue and not a Cutegram issue, I'm opening this issue here to replace https://github.com/Aseman-Land/Cutegram/issues/46

Please fix this. @leonerd already told you what's needed to support this.

**Comment by smlu** [comment]
We use this lib in my company @ZeroPass for message channel protocol and 2FA works just fine. I believe this issue should be resolved on Cutegram side.

**Comment by Flohack74** [comment]
It is not in libqtelegram-aseman-edition, it is wrong in TelegramQML...

**Comment by no-identd** [comment]
Actually it was an issue in both, fixed in #58 by @Flohack74.
